name: CustomEnchantments
version: 1.0-SNAPSHOT
main: org.deluxegaming.customenchantmentsts.CustomEnchantments
author: Nathan
commands:
  customenchantments:
    description: Manage custom enchantments.